### ISSUE TITLE
Including sdl2.h results in a linking error/IMGUI does not detect clicks

### ISSUE THREAD

**Issue by Noelswag** [CITM-UPC/Badass-Engine#1]
@pepcots I don't know if it is a problem with VCPKG or something. Adding other SDL header files like "events" works perfectly but not the main one.

This is all because I asked copilot for help with the IMGUI problem and it gave me a solution that required me to include sdl2.h.

Anyways I'd like to know why it doesn't detect my clicks, It probably has something to do with SDL, but who knows.

You can go to MyGUI.cpp and enable the demo window if you need further testing

**Comment by Noelswag** [comment]
I will add that I wasn't the one who implemented SDL, also, it does not work entirely since for example I can't close the window by pressing the X on the corner (while in the example one I can)

**Comment by pepcots** [comment]
About events not being captured:
Events are being captured in the window processEvents method.. and after this method there are no more events to capture.
If you want to porocess events externally, place the events loop externally (as you have done) and let window handle individual events
https://github.com/CITM-UPC/Badass-Engine/blob/a1b628bbedba99cdb2b7cf03e60521e6b08c068b/Maker/Editor/main.cpp#L219

**Comment by pepcots** [comment]
About linker problems after including "SDL.h" -> if you include SDL.h it will try to link to an internal "main" function. So.. don't do it unless you know what you are doing!
If you still want to use it, you will have to link it manually

**Comment by Noelswag** [comment]
> About events not being captured: Events are being captured in the window processEvents method.. and after this method there are no more events to capture. If you want to porocess events externally, place the events loop externally (as you have done) and let window handle individual events
> 
> https://github.com/CITM-UPC/Badass-Engine/blob/a1b628bbedba99cdb2b7cf03e60521e6b08c068b/Maker/Editor/main.cpp#L219

I don't really understand it. Does it mean I have to put everything outside the while? or like, remove this one?

https://github.com/CITM-UPC/Badass-Engine/blob/a1b628bbedba99cdb2b7cf03e60521e6b08c068b/Maker/Editor/main.cpp#L228

**Comment by Noelswag** [comment]
![image](https://github.com/user-attachments/assets/433bef90-d34d-4cb0-b5e7-7d37d42e3c1c)
Bueno de mientras hemos hecho esta guarrada...

**Comment by pepcots** [comment]
Is not that bad. My recomendation, you can create a processSingleEvent method for the Window and do not call "processEvents"

**Comment by pepcots** [comment]
I'll try to improve the code for the sdl example reflecting this!
